### ISSUE TITLE
widget-action and other events are increasing with each deploy

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge-nr-dashboard#102]
Due to the organisation of code, events like `widget-action` cannot be unhooked and as a result, each time a node is deployed, new events are hooked up causing duplicate, triplicate messages being posted to node-red

**Comment by Steve-Mcl** [comment]
related

The fix for #96 will also likely close this

**Comment by joepavitt** [comment]
Hmm, I had spotted this before, and definitely fixed it 🤔

Will have to dig into this again to be sure.

This would also be redundant upon us doing the event restructuring as you mentioned

**Comment by joepavitt** [comment]
Just checking this again, I definitely did "fix" this, by introducing state stored in:

```
ui.events.load[widget.id]
ui.events.action[widget.id]
ui.events.change[widget.id]
```

Will investigate why this isn't working as it should be.
