### ISSUE TITLE
React instead of Vue

### ISSUE THREAD

**Issue by malishahi** [flowforge/flowforge-nr-dashboard#125]
### Description

I'd love to develop React components instead of Vue and Bootstrap instead of Material UI. How could I contribute into this project to realise this? I am not familiar with integration of UI part with Node-RED.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Hi @malishahi - us choosing to use Vue as the foundation of the Dashboard 2.0 would be quite restrictive in this case (we had to choose one of Angular/Vue/React), can't really support multiple frameworks in a the single UI.

I have however built this such that the Node-RED side (everything in the `/nodes` folder) and UI side (`/ui`) are independent of each other.

The UI just creates a Vue App, and connected to Node-RED via SocketIO (see `ui/src/main.js` where this connection is established). [This](https://flowforge.github.io/flowforge-nr-dashboard/contributing/guides/events.html) documentation then details the events that are sent between Node-RED and the UI.

You could in theory fork, and replace the contents of `/ui` with a React App, but this is by no means a trivial task though, as all of the existing widgets are built in VueJS.
