### ISSUE TITLE
Inconsistency in Dropdown msg output

### ISSUE THREAD

**Issue by colinl** [flowforge/flowforge-nr-dashboard#127]
A few issues and questions with the dropdown node:
1. Message passthrough option is missing.
2. Is it intentional that the node output is different to the output in Dashboard 1? This node outputs an object, the old one just returned the selection value(s).
3. It isn't clear (or implemented?) how to preselect an option by passing in a required selection value.

**Comment by joepavitt** [comment]
HI @colinl just to address each of these options individually:

> Message passthrough option is missing.

You're absolutely right, we're still working through backporting all of the D1.0 options.

> Is it intentional that the node output is different to the output in Dashboard 1? 

Whilst we are basing a lot of our work on Dashboard 1.0, we are also trying to offer improvements in places, this was felt to be more verbose and potentially useful to do. If you have a case for why just the string value is cleaner/better, happy to hear it and make changes.

> It isn't clear (or implemented?) how to preselect an option by passing in a required selection value.

Right you are, that is not yet implemented.

I'll create 2 issues for (1) and (3) to ensure they're tracked individually.

**Comment by colinl** [comment]
For (2) can see the logic in having both the label and value available, less so for the type I think.  However, for myself I always keep my dashboards isolated from the control logic, using MQTT as the interface between them.  So with a D1 dropdown I can feed the selection straight into MQTT, and for pre-selection on restart I can feed from MQTT straight into the node.  Moving to D2 I will have to add Change nodes for each one to select just the value.  I wonder whether a better solution would be have a configuration option to allow either the label or the value to be emitted.

Another complication is with passing in a message to pre-select an option or options.  For the D1 widget this is done by passing in msg.payload with the option(s) to be selected.  What is proposed for this widget?  If msg pass through is selected it all becomes rather complicated if the node sends on an object rather than the value passed in.  The suggestion of a configuration option removes this issue too.

**Comment by joepavitt** [comment]
Points very well made @colinl - I'll get it updated accordingly 🙂

**Comment by colinl** [comment]
Actually, I cannot think of a reason why one would ever want to pass on the label rather than the value.  The only function the value has is to provide something to be passed on (and fed in).  If there appears to be a need to pass on the label then one just has to make the value the same as the label.
So unless my logic is flawed I think there is no need for it to be any different to the D1 dropdown.

**Comment by joepavitt** [comment]
Absolutely valid points - it's on my short term list to sort, currently working on https://github.com/flowforge/flowforge-nr-dashboard/issues/136

**Comment by colinl** [comment]
Which is indeed a most worthy task!

**Comment by joepavitt** [comment]
This issue will now be constrained to fixing the output message from dropdown to be consistent with Dashboard 1.0, and consistent with the message pass _into_ the dropdown when wanting to make a selection per #130
