### ISSUE TITLE
Switch: Add topic, indicator, and message pass through options

### ISSUE THREAD

**Issue by colinl** [flowforge/flowforge-nr-dashboard#141]
### Description

A Topic field and message pass through option need to be added to ui-switch node

### Have you provided an initial effort estimate for this issue?

I am no FlowForge team member

**Comment by colinl** [comment]
Also the Indicator options (Show state of input/ouput).
Edited title to include this.

**Comment by joepavitt** [comment]
Thanks for opening this Colin. The status indicators are implemented:

<img width="248" alt="Screenshot 2023-08-18 at 11 53 13" src="https://github.com/flowforge/flowforge-nr-dashboard/assets/99246719/d9921608-d9cc-489d-9b70-4ba24c1ec78d">

They don't seem to populate on first start of Node-RED, or when the toggle is first added to the canvas (to show off state by default) is that the same as you're experiencing?

**Comment by colinl** [comment]
Sorry, I should have been clearer, it is this (from D1 switch) that I am referring to
![image](https://github.com/flowforge/flowforge-nr-dashboard/assets/38307/e062fc10-18c2-4a10-a37b-9f2821364124)

In fact that may already be implemented, as it only appears when message pass through is disabled, which cannot be done at the moment as the option is not available.

**Comment by joepavitt** [comment]
If a switch has, for example `topic` set to a string of `Hello World`, would you expect this topic to _also_ be attached when passing a message for selection through to the switch? Or, _only_ bind that topic when an explicit UI-side change is done?

**Comment by colinl** [comment]
I don't have a strong feeling on this, but I have tested the situation with D1 and it passes on the complete message, but overwrites the topic with that from the node config.  It should only action it and pass it on if the payload matches the On or Off config in the node.

**Comment by colinl** [comment]
I don't think this is fully fixed.  The indicator selection described above (Switch icon shows state of input/output) that should appear when pass through is disabled is not there (for me at least).

**Comment by colinl** [comment]
Also the switch status shown in the editor does not always follow the switch position when a message is fed in.
Import this flow and click the inject nodes, the switch correctly changes state on the dashboard but the status in the editor does not.
```
[{"id":"7b349d5ce88ed6bf","type":"inject","z":"6e4dd70a4b804955","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"test/topic","payload":"ON","payloadType":"str","x":210,"y":920,"wires":[["f243dafd7c3b2a1a"]]},{"id":"453d7cf255841fde","type":"inject","z":"6e4dd70a4b804955","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"test/topic","payload":"OFF","payloadType":"str","x":210,"y":960,"wires":[["f243dafd7c3b2a1a"]]},{"id":"f243dafd7c3b2a1a","type":"ui-switch","z":"6e4dd70a4b804955","name":"","label":"switch","group":"ec06ac72ac8562eb","order":0,"width":0,"height":0,"passthru":false,"topic":"topic","topicType":"msg","style":"","className":"","onvalue":"ON","onvalueType":"str","onicon":"","oncolor":"","offvalue":"OFF","offvalueType":"str","officon":"","offcolor":"","x":370,"y":940,"wires":[["5568977077a8940e"]]},{"id":"5568977077a8940e","type":"debug","z":"6e4dd70a4b804955","name":"debug 23","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":560,"y":940,"wires":[]},{"id":"ec06ac72ac8562eb","type":"ui-group","name":"test","page":"46dfd140ddb08ebf","width":"6","height":"1","order":-1,"disp":false},{"id":"46dfd140ddb08ebf","type":"ui-page","name":"Test","ui":"04ee189a49c54f22","path":"/","layout":"grid","theme":"23aa79f4e489b044","order":-1},{"id":"04ee189a49c54f22","type":"ui-base","name":"Dashboard","path":"/dashboard"},{"id":"23aa79f4e489b044","type":"ui-theme","name":"Theme 1","colors":{"surface":"#ffffff","primary":"#514fba","bgPage":"#eeeeee","groupBg":"#ffffff","groupOutline":"#cccccc"}}]
```

**Comment by colinl** [comment]
If pass through is disabled, and the switch icon is set to follow the state of the input, then when the button is clicked it sends the message (on or off as appropriate) but the switch does not move.  The switch icon always displays the state of the last message received.  Typically this mode is used in a flow something like

![image](https://github.com/flowforge/flowforge-nr-dashboard/assets/38307/649827df-12d5-4750-96f4-1f0d4d21bc19)

When the switch is clicked it sends the on/off command to the appropriate device, but the switch does not immediately move.  When the command has been actioned the new state is received and switches the display.  Normally this will be so quick that it appears to be immediate, but it ensures that the displayed state always matches the state of the actual device.  The fact that the incoming message is not passed through ensures that a loop is not created.

**Comment by joepavitt** [comment]
Thanks @colinl - great description, and a clear articulation on the value there. I've opened the issue accordingly, as this is not what I had in scope (or in my mind) when we've spoken previously.
