### ISSUE TITLE
Report/Notebook Layout

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge-nr-dashboard#164]
### Description

With the addition of the template & markdown nodes, it would be great to have a Dashboard layout that enabled more reporting/Notebook style Dashboards, with dynamic content.

1024px wide max-width, 100% on smaller screens. Groups stack atop each other, with content centralised.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
This is a really great idea. I can see this being very useful for businesses. 

Couple of questions: 

* Is there an easy way to add use images?  
* Are the layouts per page or per dashboard? Sorry I forget what level they exist (hoping it is per page as that means users can have a regular dashboard with special report pages)

**Comment by joepavitt** [comment]
> Are the layouts per page or per dashboard?

Layouts are per page, so can have some "normal" Dashboards, some report, etc.

> Is there an easy way to add use images?

Not at the moment, other than referencing an externally hosted image through standard markdown/img syntax, although this has been requested [here](https://github.com/flowforge/flowforge-nr-dashboard/issues/8) too, and is being treated as a separate issue.

**Comment by Steve-Mcl** [comment]
brill. 👏 

PS, on the images - there is a stop gap way:

`file in`  → `base64`  → `template` `<img ...`

or using `node-red-image-tools` 

`image` node → `template` `<img ...`
