### ISSUE TITLE
Blank Text Fields for Custom Headlines and Descriptions

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/flowforge-nr-dashboard#17]
### Description

I suggest adding blank text fields for headlines and descriptions, enabling users to create custom content. These fields should:

- Be easy to locate and access within the content creation/editor interface.
- Have an appropriate character limit to ensure the custom content fits within the design layout.
- Allow for basic text formatting options, such as bold, italic, and underline.
- Support input validation to prevent inappropriate content or formatting issues.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Support for markdown would be great in such a widget.

**Comment by joepavitt** [comment]
Markdown widget was added in: https://github.com/flowforge/flowforge-nr-dashboard/pull/62

**Comment by joepavitt** [comment]
Given this can now be achieved using Markdown, I'm going to close this out.
