### ISSUE TITLE
Add Duration Option to Charts

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge-nr-dashboard#173]
### Description

See: https://discourse.nodered.org/t/dashboard-2-0-pre-alpha-available/80142/104?u=joepavitt

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
Without something to limit the number of points in a chart (which is what the duration in v1 does), web pages become unresponsive very quickly.

Consider someone sending a voltage or temperature every 10 sec to a chart. After 1 day, the chart is trying to render 14400 points in a pixel space of (for example) 300.  

There are many threads on the forum about "slow dashboard" and almost always, the first question is, how much data are you trying to display & what size is the chart.
