### ISSUE TITLE
Add topic to Slider and Input like RadioGroup and Dropdown have

### ISSUE THREAD

**Issue by christiaanwesterbeek** [flowforge/flowforge-nr-dashboard#177]
### Description

The Slider and Input node do not have a topic like for example a RadioGroup and Dropdown have. It is convenient for some nodes, like [node-red-contrib-dynamic-thermostat](https://flows.nodered.org/node/node-red-contrib-dynamic-thermostat) that the different payloads are accompanied with a topic. Currently I am adding a function node after Slider and Input to add the missing topic.

Slider|Input|Dropdown
---|---|---
<img width="410" alt="image" src="https://github.com/flowforge/flowforge-nr-dashboard/assets/465989/a5219b85-26dc-46e3-a5ca-28395fd760cd">|<img width="413" alt="image" src="https://github.com/flowforge/flowforge-nr-dashboard/assets/465989/19cd6c0c-e63a-4c7d-8531-88dc36288afb">|<img width="479" alt="image" src="https://github.com/flowforge/flowforge-nr-dashboard/assets/465989/84ddec81-c94e-46e3-bb1d-801a92083493">

PS: I am a programmer, but relatively new to node-red, so I maybe overlooking something.

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by joepavitt** [comment]
Thanks for raising the issue, actually fixing that as we speak as part of the fix for #141 - will be in today/tomorrow.
