### ISSUE TITLE
Use in control systems

### ISSUE THREAD

**Issue by chaoticgoodly** [flowforge/flowforge-nr-dashboard#29]
In my industry, we use Node-RED for audiovisual control systems (similar to home automation, but in a commercial setting with much more polish required). While these control systems are often backend-only, we commonly need to provide user GUIs as well. These would typically run in a kiosk web browser on an embedded touch panel, but it could also run on a user's device. Sometimes we run a Node-RED instance 1:1 per AV system. Sometimes we have one instance that may be serving events and control for dozens or hundreds of systems (using query params / path to specify which system is being used). Dashboard provides a nice way of doing this without requiring each developer to understand front-end development, as opposed to ui-builder for example. I'd love for the successor to Dashboard to bear in mind that interactive GUIs is a major use case for us, not just data visualization, and that a low-code approach is highly desirable. We should be able to bring our own components, but also take advantage of a rich palette of existing components. I'd love to see something React based but that's not a strict requirement. 

Feel free to take from this what helps. Just sharing context for future development.

**Comment by rcarmo** [comment]
As someone who codes a simple UI for pretty much every back-end service I develop, I wholeheartedly support this (I also use dynamic screens for my home automation, but the ease of just getting something going and iterating without coding is paramount in those inner loop scenarios).

**Comment by chaoticgoodly** [comment]
@joepavitt I'm excited to see movement on this project! You're welcome to close this issue at your leisure, it was more food for thought than anything 😀 

Good luck and congrats on the 0.0.1 release!

**Comment by joepavitt** [comment]
Thanks for the nudge @chaoticgoodly, had missed this issue. Will address a couple of your points in a bit of detail:

> but also take advantage of a rich palette of existing components

My plan/priority is to be porting over the existing collection of components from Dashboard 1.0. Whilst they're not going to be backward compatible re: flows, they should behave and interact in exactly the same way. Some customisations likely to be missing at the start, but we'll get there.

You can see a list of interactive elements I'm working through here: https://github.com/flowforge/flowforge-nr-dashboard/issues/9#issuecomment-1550981539

You can also find a list of the widgets we'e got so far (including screenshot examples) here in the documentation: https://flowforge.github.io/flowforge-nr-dashboard/

> I'd love to see something React based but that's not a strict requirement.

I've chosen to go ahead with Vue over React. I could write an essay about this, but it was well thought through and discussed heavily with @dceejay. The highlight points were:

- Vue more similar to Angular v1.0 in it's coding patterns, so more familiar with existing community for when they want to write templates
- Shallower learning curve for Vue than React, and generally considered more friendly to non front-end devs
- Clearer separation of html/css/js and makes for easier readability in a community project, especially where contributors may not be expert front-end engineers.
- Also used by FlexDash and UI Builder, which are the alternative Dashboard tools in Node-RED, so would make this project also more appealing to existing users of those tools.

**Comment by chaoticgoodly** [comment]
Nice, thanks for the comment. All makes sense to me! Good luck on the project! I'll stay tuned 🤘🏻
