### ISSUE TITLE
Class support

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge-nr-dashboard#78]
### Description

Please add support for appling classes to the widgets.  

This opens up lots of capability (and plugs holes in missing capabilities)

### Reasoning

Many many threads on the forum start off with "how do I make something green when msg.payload is `true`", "how do I hide a group based on a msg property" etc etc.  

The most popular answer is "Add a `css` class named `green`, send the node a msg that adds the "green" class. 

### NOTES

In current dashboard, CSS Classes are added in a `head` or `regular` section using the ui-template node

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Closed by #169
