### ISSUE TITLE
Link to dashboard

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge-nr-dashboard#79]
### Description

It is not easy to access dashboard from the NR editor. It would be very useful to have a URL on the edit dialog of each widget that links out to the correct URL.  

The hyperlink should use "_blank" as its target, or, better still, a named "target" to reuse any already opened dashboard (i.e. avoid multiple tabs/windows being created)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by bartbutenaers** [comment]
Hi @Steve-Mcl,

For the old dashboard I have always used the [node-red-contrib-plugin-header](https://flows.nodered.org/node/node-red-contrib-plugin-header), which offers a button in the flow editor header to access the dashboard quickly.  I assume something similar could be used for this new dashboard...

Bart
