### ISSUE TITLE
Config settings not fully propagated when using node / flow deploy

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge-nr-dashboard#81]
When changing a page config from grid -> flex / flex -> grid, follwoed by a node or flow deploy, changes are not fully propagated to all dependant nodes and the dashboard does not get full and up-to-date config.

1. Create a page - set layout to "flow" mode - name it PAGE1
2. add a few unconnected ui nodes that uses PAGE1
3. deploy and view page
4. edit one node -> page config, set the layout to "grid"
5. do a node deploy
6. check the config in the browsers console - other nodes config are not updated.

**Comment by joepavitt** [comment]
Fixed in https://github.com/flowforge/flowforge-nr-dashboard/pull/120
