### ISSUE TITLE
dashboard breaks all nodes using an editor

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge-nr-dashboard#86]
When installed, any nodes using the RED.editor breaks

https://github.com/flowforge/flowforge-nr-dashboard/assets/44235289/a722b691-a36f-4bfe-8e38-2da632b94f68

---

Dashboard2 v0.0.4
Node-RED 3.1.0-beta.4
Chrome latest
Node 16

**Comment by joepavitt** [comment]
Any idea why this might be occurring Steve?

**Comment by Steve-Mcl** [comment]
My guess is prototype pollution. It's why I want to wrap all the code in the html scripts in IIFEs (encapsulate all the globals)
