### ISSUE TITLE
Moving Slider results in a loop

### ISSUE THREAD

**Issue by Paul-Reed** [flowforge/flowforge-nr-dashboard#89]
Just installed on a Oracle Cloud server running Ubuntu, Node-RED version: v3.0.2 and Node.js  version: v16.20.0.
Installed OK, but had a problem with the Slider.
Visually, it's missing the 'continuously while sliding/only on release' option which appears to be [defined here](https://github.com/flowforge/flowforge-nr-dashboard/blob/main/nodes/widgets/ui_slider.html#L88&L94), and when I move the slider, it runs into a loop, and I then need to delete the node to recover stability.
See [Gif posted in NR Forum](https://discourse.nodered.org/t/dashboard-2-0-pre-alpha-available/80142/16) for demo.

**Comment by Paul-Reed** [comment]
...I've also attached the gif screenshot here...

![mytest](https://github.com/flowforge/flowforge-nr-dashboard/assets/973580/fa873404-dab3-4a60-94fd-1e09f757a610)

**Comment by joepavitt** [comment]
Hi @Paul-Reed would you be able to try out v0.0.6 that I released last night please? I've copied your flow and setup, and wasn't able to reproduce the problem annoyingly, even on 0.0.5, but I did make some changes to how events are passed between NR and the UI yesterday, that _may_ help with this issue.

**Comment by Paul-Reed** [comment]
Yes, it's working fine now with v0.0.6.

![mytest](https://github.com/flowforge/flowforge-nr-dashboard/assets/973580/5e0bf7c9-97c3-44f6-89cf-a200a12ce462)

Thanks Joe
