### ISSUE TITLE
Interactive elements

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/flowforge-nr-dashboard#9]
## Describtion 
To increase the interactivity and user engagement of the Dashboard / App Builder, I propose the addition of easy-to-use and customizable buttons (interactive elements). This feature would enable users to quickly create buttons that can perform specific actions or trigger events within the dashboard, making the overall experience more interactive and dynamic.

**Comment by rcarmo** [comment]
Allow me to suggest to add a simple text link (or the ability to set one to a label) as one of the baseline components (I assume labels are going to be an integral part of this). 

When linking to external pages (or even to set an anchor to jump to other parts of the dashboard), something that is less obtrusive than a button is often desirable. My typical use case is to add an external link to documentation/reference as part of a form.

**Comment by joepavitt** [comment]
We could add this functionality to the "ui_text" widget that's already available? Would provide the same formatting options, etc. that would likely be shared across the two components (if a separate component) anyway.

**Comment by joepavitt** [comment]
Closing this higher level item out as we have most of the interactive elements built, any remaining items have individual trackers/issues with their own respective priorities attached.
