### ISSUE TITLE
EventEmitter Memory Leak

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge-nr-dashboard#96]
### Description

```sh
(node:93636) MaxListenersExceededWarning: Possible EventEmitter memory leak detected.
11 disconnect listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
```

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
As discussed, since we have a map of components in ui-base, we _should_ be able to subscribe to events once in the ui-node, then dish out any incoming events to widgets by the mappings in node.ui.widgets - meaning we dont have a subscription for every single node.

**Comment by joepavitt** [comment]
Just assigning you Steve as you looked into this recently, just trying to get the backlog in order a litte.
